### ISSUE TITLE
Invalid log levels

### ISSUE THREAD

**Issue by AnonymusRaccoon** [IonxSolutions/serilog-sinks-syslog#40]
I just started to use this sink, but when using the LocalSyslog(), the journalctl report invalid levels. The Log.Verbose() is mapped to a higher importance than Log.Information(). Here is what log levels look like in a local journalctl instance:

![journalctl](https://user-images.githubusercontent.com/32224410/131853525-0080a08b-65a8-4b09-a998-04f23f078885.png)

This could be fixed by changing the code at [SyslogFormatterBase.MapLogLevelToSeverity](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/3589290dfad2dbab536d2a51009478e64646036f/src/Serilog.Sinks.Syslog/Sinks/Formatters/SyslogFormatterBase.cs#L51) to this:
```csharp
private static Severity MapLogLevelToSeverity(LogEventLevel logEventLevel)
            => logEventLevel switch
            {
                LogEventLevel.Verbose => Severity.Debug,
                LogEventLevel.Debug => Severity.Informational,
                LogEventLevel.Information => Severity.Notice,
                LogEventLevel.Warning => Severity.Warning,
                LogEventLevel.Error => Severity.Error,
                LogEventLevel.Fatal => Severity.Emergency,
                _ => Severity.Notice
            };
```
but it breaks tests (since tests expect another severity level) so I am not sure if I should PR or not.

**Comment by Kevin-Andrew** [comment]
@AnonymusRaccoon 

I think your proposed mapping of:
```
LogEventLevel.Debug => Severity.Informational,
```
seems a bit odd. Can we instead map both `Verbose` and `Debug` to `Severity.Debug`?
```
LogEventLevel.Verbose => Severity.Debug,
LogEventLevel.Debug => Severity.Debug,
```
and then keep all the others the same?

You also changed `LogEventLevel.Information` from `Severity.Informational` to `Severity.Notice`. Why? That is what is causing the Unit Test failures.

So my proposal would be to simply add:
```
LogEventLevel.Verbose => Severity.Debug,
```
to the top of the list and end up with:
```
private static Severity MapLogLevelToSeverity(LogEventLevel logEventLevel)
    => logEventLevel switch
    {
        LogEventLevel.Verbose => Severity.Debug,
        LogEventLevel.Debug => Severity.Debug,
        LogEventLevel.Error => Severity.Error,
        LogEventLevel.Fatal => Severity.Emergency,
        LogEventLevel.Information => Severity.Informational,
        LogEventLevel.Warning => Severity.Warning,
        _ => Severity.Notice
    };
```

Then all the Unit Tests pass.
![image](https://user-images.githubusercontent.com/22459191/131876664-9c4efad3-7053-4fd1-bbe0-04065b803f9d.png)

Will that work for your **journalctl**? (I don't know what that is or why it reports invalid levels.)

**Comment by AnonymusRaccoon** [comment]
Journalctl is the standard tool to read syslogs on linux.

Journalctl report invalid levels because the verbose level is mapped to "notice" (log level 5) while the information level is mapped to "info" (log level 6).
In syslogs, levels are emerg (0), alert (1), crit (2), err (3), warning (4), notice (5), info (6) and debug (7).

I proposed to map Information to Notice to reflect the difference of log level on the syslog even if the two names don't match. Having both Verbose and Debug map to Debug will be fine, but there will be no way to differentiate the two.

**Comment by Kevin-Andrew** [comment]
Can you elaborate more on:
> ...the journalctl report invalid levels.

A Syslog RCF3164 formatted message may look like:
```
<14>Sep  2 20:52:39 SG4KEVDEVLOCAL SPP[3860]: some message
```
and the corresponding source code in my application that generated that message was simply:
```
Serilog.Log.Information("some message");
```
So from the `<14>` in the Syslog message, we can divide by 8 and get 1 for the `Facility` and a remainder of 6 for the `Severity`. Those map to `user-level` and `Informational`.

If instead my source code was:
```
Serilog.Log.Verbose("some message");
```
the corresponding Syslog message, using the current version of this `IonxSolutions/serilog-sinks-syslog` project, would be:
```
<13>Sep  2 20:52:39 SG4KEVDEVLOCAL SPP[3860]: some message
```
Taking the `<13>` and doing the same math, we get 1 for the `Facility` and a remainder of 5 for the `Severity`. Those map to `user-level` and `Notice`, which as you know is what the code is currently doing and what you're reporting an issue with, to my understanding.

The thing I don't understand is how can **Journalctl** be reporting some kind of _invalid level_? How does it know anything about my program's source code, the one with `Serilog.Log.Verbose("some message");` and can say that, "Hey, `Verbose` is mapped to Severity `Notice`, and that can't be because the Serilog `Information` level is mapped to Syslog Severity `Informational`, which is less than `Notice`."

Here is another Syslog _reader/listener_, it has no problem reporting `Notice`.
![image](https://user-images.githubusercontent.com/22459191/131924277-a3596a28-d0f9-4d31-b6ad-66d485f04058.png)

I don't disagree that having `Verbose` mapped to `Notice` is a bit strange, but if you change any of the mappings, it can technically be considered a breaking change because other people may have their Syslog configured to act on certain events based upon the `Severity` level, and your proposed change of changing `Information` to `Notice` and `Debug` to `Informational` would cause the [Syslog Priority part](https://datatracker.ietf.org/doc/html/rfc3164#section-4.1.1) to change, and people's events/alarms can get screwed up, just like the Unit Tests failing.

I'm sorry I don't know any more about **Journalctl** to understand your problem. But hopefully we can discuss more and figure something out.

**Comment by AnonymusRaccoon** [comment]
True, the journal does not know what is the source code, so it's won't report invalid log levels but as a user, I expect Information messages to have a higher importance than Verbose messages.

Syslogs can be filtered by priority, so someone might want to see "logs with an importance higher or equal to Notice" and they will see errors, warnings and verbose messages. I usually use verbose messages to report very useless stuff that might help debug, this is not the kind of messages that should be shown to the end-user when they request notice levels.  Information messages are more appropriate for this behavior.

This is also why I think that the Syslog's Information level should be mapped to Notice instead of having both Debug and Verbose map to Debug, to keep the ability to filter logs by their level.

It is indeed a breaking change (that's also why I raised an issue instead of a PR) but I believe that the default behavior should be to keep levels in the right order (so Verbose > Debug > Information > Warning > Error > Fatal and not Debug > Information > Verbose > Warning > Error > Fatal).

**Comment by Kevin-Andrew** [comment]
> True, the journal does not know what is the source code, so it's won't report invalid log levels but as a user, I expect Information messages to have a higher importance than Verbose messages.

Thank you, that helps explain things to me.

@colin-anderson , do you want to weigh in on whether you want to make a code change that some may consider a "_breaking change_"?

@AnonymusRaccoon , I can think of a few possible alternatives.
1. You can declare your logger such that the minimum level logged is `Debug`, thus ignoring any `Verbose` logs being sent to your Syslog server in the first place.
```
var logger = new LoggerConfiguration().MinimumLevel.Debug();
logger.WriteTo.UdpSyslog(...); // Or whatever.
```
2. We provide some kind of override capability for the mapping of the log level to severity.
3. And lastly, one that you can do right now, you can implement your own `ISyslogFormatter` class and provide whatever mapping you want. You mentioned you were using the `LocalSyslog()`, so we can use the `LocalFormatter` as an example:
```
public class LocalFormatterWithAdjustedPriority : Serilog.Sinks.Syslog.SyslogFormatterBase
{
    // Need our own copy since it's not exposed in the base class to us.
    private readonly Facility facility;

    public LocalFormatter(Facility facility = Facility.Local0,
        MessageTemplateTextFormatter templateFormatter = null)
        : base(facility, templateFormatter)
    {
        this.facility = facility;
    }

    public override string FormatMessage(LogEvent logEvent)
        => RenderMessage(logEvent);

    // Notice the use of the new keyword since this method in the base class isn't virtual.
    public new int CalculatePriority(LogEventLevel level)
    {
        var severity = MapLogLevelToSeverity(level);
        return ((int)this.facility * 8) + (int)severity;
    }

    private static Severity MapLogLevelToSeverity(LogEventLevel logEventLevel)
        => logEventLevel switch
        {
            // Your proposed mappings here or anything else you want.
            LogEventLevel.Verbose => Severity.Debug,
            LogEventLevel.Debug => Severity.Informational,
            LogEventLevel.Information => Severity.Notice,
            LogEventLevel.Warning => Severity.Warning,
            LogEventLevel.Error => Severity.Error,
            LogEventLevel.Fatal => Severity.Emergency,
            _ => Severity.Notice
        };
}
```
That is untested code, but hopefully it's close to what you need.

**Comment by colin-anderson** [comment]
@Kevin-Andrew it's an oversight that `LogEventLevel.Verbose` isn't explicitly mapped, and @AnonymusRaccoon is certainly correct that having Serilog's `Verbose` mapped to `Notice` is not ideal 😨

Ideally, the mappings would be changed to those proposed by @AnonymusRaccoon, but I'm a little wary of changing the mapping for `LogEventLevel.Information` in particular, since it's likely to be used a *lot*; I'd guess very few will be logging `Verbose` level messages to Syslog though (because of sheer volume), so it's an easier decision to remap that now.

I think the approach is:

1. Remap `LogEventLevel.Verbose` to `Severity.Debug` for now
2. Provide a new extensibility point that allows plugging in your own level mapper (happy to take a PR :smile:)
    - Ship 2 mapper implementations by default: one labelled "Standard" (which would use @AnonymusRaccoon's proposed mappings), and another labelled "Compatibility" which would use the current mappings
    - We'd default to the "Compatibility" mapper for now
3. Document the new extensibility point, and intent to switch the default to the "Standard" mapper in version 3.0.0
4. When we later release 3.0.0 (which would also add a .NET 6.0 target as per #24), we default to the "Standard" mapper, but keep the "Compatibility" mapper so devs can easily switch to it if wanted

This way we quickly fix the issue of `Verbose` being logged at a higher Syslog severity than `Debug`, and medium-term we fixup the mappings properly without breaking existing deployments, while *also* making it configurable.

Thoughts?

**Comment by Kevin-Andrew** [comment]
@colin-anderson @AnonymusRaccoon 

Three and a half years and this is the first time someone is commenting on the mappings. And I don't consider it a technical issue. It is an interpretation/definition of the meaning of a value. For example, [in the man pages of Syslog](https://www.gnu.org/software/libc/manual/html_node/Overview-of-Syslog.html) it states:
> priority
Except for the fact that the priorities have a defined order, **the meaning of each of these priorities is entirely determined by the system administrator.**

There is nothing preventing someone from saying, "Hey, in our system `Verbose` means `Notice`".

I would much more prefer to have the names of the enumerations match as much as possible. Most people aren't going to know the Syslog `Severity` levels, but at a quick glance, they are going to see that 4 names match and will probably assume they map directly and would consider anything else a bug if the names don't match.

With the current mapping, we get 4 names that map name for name. With the proposed future mapping, there are only 2 names that match. I think it is far more likely for people to comment on those not matching when the names exist in both.  Also, I think the 2 name matches that we would loose are probably used most often. In one of our solutions with over 350,000 lines of code, we have the following:
`Verbose` used 3 times
`Debug` used 1,604 times
`Information` used 1,207 times
`Warning` used 126 times
`Error` used 722 times
`Fatal` used 8 times

Our `Debug` and `Information` log entries would no longer match the `Severity` name in Syslog, and I would hate to have to explain to all of my co-workers **and** customers **and** customer support that whenever our code writes something to `Debug`, that it actually comes out of Syslog as `Information` and that `Information` actually comes out as `Notice`.

And while you may say, "That is why we are proposing the **extensibility points**", I think doing everything you propose is a lot of work and will consist of code that introduces more noise and will have to be carried forward in future versions. Not to mention immediately introducing one problem for another with the changing of `Verbose` to `Severity.Debug` and the fact that `Severity.Debug` will now have two `EventLogLevel`s mapped to it, thus not being able to distinguish between them.

Also note that by default, `Verbose` log entries are ignored. That is, when you create a logger with:
```
var logger = new LoggerConfiguration();
```
and try to use it with one of the extension methods:
```
logger.WriteTo.UdpSyslog(IPAddress.Loopback.ToString(),
    receiver.ListeningIPEndPoint.Port,
    format: SyslogFormat.RFC3164);
```
[The default minimum level is](https://github.com/serilog/serilog/blob/v2.0.0/src/Serilog/LoggerConfiguration.cs#L38) `Information`. So to change that, one must declare the logger like:
```
var logger = new LoggerConfiguration().MinimumLevel.Verbose();
```
I think if you're doing that, you can also write your own small class to override the `Severity` mapping if needed.

I think what we can offer as the **extensibility point**, is to simply mark the `CalculatePriority()` method as `virtual` (and the `facility` member variable as `protected`). Then, the example I gave in [my comment above](https://github.com/IonxSolutions/serilog-sinks-syslog/issues/40#issuecomment-912662098) would `override` the `CalculatePriority()` method. Or a slightly shorter implementation could be to inherit from `Rfc3164Formatter` instead of `SyslogFormatterBase`.

So we wouldn't have to worry about breaking others, nor trying to explain that there will be a breaking change in the next major release, nor having additional code carried forward with yet more additional configuration options.

Having said all of that, I went ahead and implemented different approaches to try and see what we might like the best.
1. A [new enumeration type is declared](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/b9297777e30b261cd5ea6fe525c4d1aceee9a6a6#diff-0c7617b7de0dd596cf9cb3ac14ba7e4d5649c202e2b655dfa451f09003d5201bR14) `public enum LogEventLevelToSeverityMapping`. It is [added as an optional parameter to all of the extension methods](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/b9297777e30b261cd5ea6fe525c4d1aceee9a6a6#diff-6e8295cc73931c68d092486cbd816660e72cde08e972e20f83185b1d103e93f4R53), and then [also passed to all of the formatter's constructors as an optional parameter](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/b9297777e30b261cd5ea6fe525c4d1aceee9a6a6#diff-3d22adf4df742d9fef83214bb9769710d163b4b5ac9b2dabadbf08d9497c3145R35). Ultimately [making its way into the](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/b9297777e30b261cd5ea6fe525c4d1aceee9a6a6#diff-2d7e7ce63096a26c948122000753cb99d5dfbe386d4186a37625fb62d59032f5R34) `SyslogFormatterBase` since all formatters derive from it. That base class [then implements and provides all the mapping logic for the different enumeration values](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/b9297777e30b261cd5ea6fe525c4d1aceee9a6a6#diff-2d7e7ce63096a26c948122000753cb99d5dfbe386d4186a37625fb62d59032f5R72).
So, an example usage would be:
```
var logger = new LoggerConfiguration();

logger.WriteTo.UdpSyslog(IPAddress.Loopback.ToString(),
    receiver.ListeningIPEndPoint.Port,
    format: SyslogFormat.RFC3164,
    severityMapping: LogEventLevelToSeverityMapping.VerboseToDebug);
```
2. Second option is instead of providing a new enumeration and implementing the different possible mappings ourselves, we instead let the caller do it with a callback method: `Func<LogEventLevel, Severity> severityMapping`. This [is again added as an optional parameter to all of the extension methods](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/99757d605c4be68da0b220e656ec007711d22246#diff-6e8295cc73931c68d092486cbd816660e72cde08e972e20f83185b1d103e93f4R88) and ultimately [makes its way into the](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/99757d605c4be68da0b220e656ec007711d22246#diff-2d7e7ce63096a26c948122000753cb99d5dfbe386d4186a37625fb62d59032f5R34) `SyslogFormatterBase` class. Inside of the `CalculatePriority`, [this anonymous callback method will be called](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/99757d605c4be68da0b220e656ec007711d22246#diff-2d7e7ce63096a26c948122000753cb99d5dfbe386d4186a37625fb62d59032f5R50), invoking either the user's supplied implementation, or the built-in default. An [example usage is](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/99757d605c4be68da0b220e656ec007711d22246#diff-5a6f8dce814d7cdcb7c2633b9a70f91689a434812636d6d2d886e2df263d9622R145):
```
var logger = new LoggerConfiguration();

logger.WriteTo.UdpSyslog(IPAddress.Loopback.ToString(),
    receiver.ListeningIPEndPoint.Port,
    format: SyslogFormat.RFC3164,
    severityMapping: level =>
    level switch
    {
        // Here we also map Verbose to Severity.Debug.
        LogEventLevel.Verbose => Severity.Debug,
        LogEventLevel.Debug => Severity.Debug,
        LogEventLevel.Information => Severity.Informational,
        LogEventLevel.Warning => Severity.Warning,
        LogEventLevel.Error => Severity.Error,
        LogEventLevel.Fatal => Severity.Critical,
        _ => throw new ArgumentOutOfRangeException(nameof(level), $"The value {level} is not a valid LogEventLevel.")
    });
```
3. In [this third option, I have only made the `CalculatePriority` method of the `SyslogFormatterBase` base class `virtual`](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/b7e22a0612aec1fbf300b10aec6c5880c7b917ce#diff-2d7e7ce63096a26c948122000753cb99d5dfbe386d4186a37625fb62d59032f5R45). Example usage [involves declaring your own class, easily deriving from one of the existing formatter classes](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/b7e22a0612aec1fbf300b10aec6c5880c7b917ce#diff-dab359dd2f4c002b7676cf6a9148853a4fda17f0329bb860933f78b56c7b4384R71) where you can write your own mapping logic. You won't be able to use any of the extension methods with the custom formatter class since there isn't a parameter for that (I think there are already enough parameters). So you [would have to write a few lines manually](https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/b7e22a0612aec1fbf300b10aec6c5880c7b917ce#diff-5a6f8dce814d7cdcb7c2633b9a70f91689a434812636d6d2d886e2df263d9622R60):
```
var logger = new LoggerConfiguration().MinimumLevel.Verbose();

// Use a custom formatter class to change the mapping of the Severity.
var formatter = new CustomSeverityMappingFormatter(Facility.User);

var syslogUdpSink = new SyslogUdpSink(new IPEndPoint(IPAddress.Loopback, receiver.ListeningIPEndPoint.Port), formatter);
var sink = new PeriodicBatching.PeriodicBatchingSink(syslogUdpSink, SyslogLoggerConfigurationExtensions.DefaultBatchOptions);

logger.WriteTo.Sink(sink);
```

I was going to try and do a fourth example, that is similar to the first, but instead of introducing an entire new enumeration type, we would instead add new values to the existing `SyslogFormat` enum. For example:
```
public enum SyslogFormat
    {
        /// <summary>
        /// Writes to the local Linux libc syslog().
        /// </summary>
        Local,

        /// <summary>
        /// Writes to the local Linux libc syslog(). The mapping of <see cref="Events.LogEventLevel.Verbose"/> has been
        /// mapped to <see cref="Severity.Debug"/> instead of <see cref="Severity.Notice"/>. <see cref="Events.LogEventLevel.Debug"/>
        /// also remains mapped to <see cref="Severity.Debug"/>, meaning you won't be able to tell the difference between them.
        /// </summary>
        /// <remarks>
        /// LogEventLevel.Verbose => Severity.Debug
        /// LogEventLevel.Debug => Severity.Debug
        /// LogEventLevel.Information => Severity.Informational
        /// LogEventLevel.Warning => Severity.Warning
        /// LogEventLevel.Error => Severity.Error
        /// LogEventLevel.Fatal => Severity.Emergency
        /// </remarks>
        LocalWithVerboseToDebugMapping,

        /// <summary>
        /// Writes to the local Linux libc syslog(). Mapping between <see cref="Events.LogEventLevel"/> and
        /// <see cref="Severity"/> is done in increasing order of the enums. Most names will not match. This
        /// will become the default in the next major release.
        /// </summary>
        /// <remarks>
        /// LogEventLevel.Verbose => Severity.Debug
        /// LogEventLevel.Debug => Severity.Informational
        /// LogEventLevel.Information => Severity.Notice
        /// LogEventLevel.Warning => Severity.Warning
        /// LogEventLevel.Error => Severity.Error
        /// LogEventLevel.Fatal => Severity.Emergency
        /// </remarks>
        LocalWithValueOrderMapping,

        RFC3164,

        RFC5424
    }
```
I thought the `format` parameter was available on all of the extension methods, but it isn't. So this approach doesn't save as much as I thought it would compared to the first option.

So for me, I like the second option the best because it is the least amount of code change, it offers the most amount of flexibility (although it must be written by the caller themselves), and doesn't introduce a breaking change now nor in the future.

**Comment by colin-anderson** [comment]
Apologies for the very late response on this, production stuff took over for a while!

> Second option is instead of providing a new enumeration and implementing the different possible mappings ourselves, we instead let the caller do it with a callback method: Func<LogEventLevel, Severity> severityMapping. This is again added as an optional parameter to all of the extension methods and ultimately makes its way into the SyslogFormatterBase class. Inside of the CalculatePriority, this anonymous callback method will be called, invoking either the user's supplied implementation, or the built-in default.

On reflection, what I had previously suggested was perhaps the most "obvious" to me at the time, but yes, also a _lot_ of work 😅  I discussed with some colleagues, and we are all agreed on your option #&#8203;2 - @AnonymusRaccoon, do you fancy having a crack at a PR?

**Comment by Kevin-Andrew** [comment]
@colin-anderson @AnonymusRaccoon 

I thought you might like option 2, and I'd be willing to do it as well since I think it is the least intrusive (aside from just making the method `virtual`). I have a commit for it already in my forked repo, along with a bunch of Unit Tests:

https://github.com/Kevin-Andrew/serilog-sinks-syslog/commit/99757d605c4be68da0b220e656ec007711d22246#diff-6e8295cc73931c68d092486cbd816660e72cde08e972e20f83185b1d103e93f4R88

I'll review it one more time and can put up a PR for it and let you know.

**Comment by AnonymusRaccoon** [comment]
@Kevin-Andrew I like your PR, but I think that MapLogLevelToSeverity should be public and renamed to something like "CompatibilityMapper" and another public method that map to the levels specifiied [here](https://github.com/IonxSolutions/serilog-sinks-syslog/issues/40#issue-986747661) should be implemented. That would allow users to rapidly switch from the old behavior to the new one.

**Comment by Kevin-Andrew** [comment]
@AnonymusRaccoon @colin-anderson 
I have created PR #42 . It contains a new parameter added to each of the configuration extension methods, [here on the `LocalSyslog()`](https://github.com/IonxSolutions/serilog-sinks-syslog/pull/42/files#diff-6e8295cc73931c68d092486cbd816660e72cde08e972e20f83185b1d103e93f4R55), [here on the `UdpSyslog()`](https://github.com/IonxSolutions/serilog-sinks-syslog/pull/42/files#diff-6e8295cc73931c68d092486cbd816660e72cde08e972e20f83185b1d103e93f4R91), and [here on the `TcpSyslog()`](https://github.com/IonxSolutions/serilog-sinks-syslog/pull/42/files#diff-6e8295cc73931c68d092486cbd816660e72cde08e972e20f83185b1d103e93f4R163).

I also created a publicly available mapping like you suggested [here](https://github.com/IonxSolutions/serilog-sinks-syslog/pull/42/files#diff-6e8295cc73931c68d092486cbd816660e72cde08e972e20f83185b1d103e93f4R190). It can be used like the following:
```
var logger = new LoggerConfiguration();

logger.WriteTo.UdpSyslog(IPAddress.Loopback.ToString(),
    receiver.ListeningIPEndPoint.Port,
    format: SyslogFormat.RFC3164,
    severityMapping: level => SyslogLoggerConfigurationExtensions.ValueBasedLogLevelToSeverityMap(level));
```
