### ISSUE TITLE
Log scope and Enrich

### ISSUE THREAD

**Issue by GaryHughes** [IonxSolutions/serilog-sinks-syslog#41]
Hi I'm using Serilog with Microsofts ILogger interface and I've just started using ILogger.BeginScope to add context to log messages with the following config.

```
"WriteTo":
        [
            {
                "Name": "Console",
                "Args":
                {
                    "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss.fff} {Level:u4}] {CorrelationId}{Message:lj}{NewLine}{Exception}"
                }
            }
        ],
        "Enrich": [
            "FromLogContext"
        ]
```

And this snippet of code to start a scope.

```
ILogger logger = ...
var context = new Dictionary<string, object>() { ["CorrelationId"] = "<MY_CORRELATION_ID>" };
using var scope = logger.BeginScope(context);
```

This works nicely and my console (and file with more config) log messages have the CorrelationId inserted as expected. However when I use a syslog target the CorrelationId does not appear. 

 ```
"WriteTo":
        [
            {
                "Name": "LocalSyslog",
                "Args":
                {
                    "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {CorrelationId}{Message:lj} {NewLine}{Exception}",
                    "format": "RFC5424",
                    "appName": "blah",
                    "facility": "99"
                }
            }
        ],
        "Enrich": [
            "FromLogContext"
        ]
```

Is this expected to work with the syslog sink?

Thanks,

**Comment by Kevin-Andrew** [comment]
@GaryHughes , I believe the problem is due to the configuration you have. Unfortunately, I am not familiar with, nor have I ever used the JSON style configuration that you have provided, I only ever use C# code directly. However, based upon my understanding, your following configuration of:
```
"WriteTo":
       [
           {
               "Name": "LocalSyslog",
               "Args":
               {
                   "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {CorrelationId}{Message:lj} {NewLine}{Exception}",
                   "format": "RFC5424",
                   "appName": "blah",
                   "facility": "99"
               }
           }
       ],
       "Enrich": [
           "FromLogContext"
       ]
```

effectively [invokes the following extension method](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/master/src/Serilog.Sinks.Syslog/SyslogLoggerConfigurationExtensions.cs#L50):
```
        public static LoggerConfiguration LocalSyslog(this LoggerSinkConfiguration loggerSinkConfig,
            string appName = null, Facility facility = Facility.Local0, string outputTemplate = null,
            LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum)
        {
            if (!RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                throw new ArgumentException("The local syslog sink is only supported on Linux systems");

            var formatter = GetFormatter(SyslogFormat.Local, appName, facility, outputTemplate);
            var syslogService = new LocalSyslogService(facility, appName);
            syslogService.Open();

            var sink = new SyslogLocalSink(formatter, syslogService);

            return loggerSinkConfig.Sink(sink, restrictedToMinimumLevel);
        }
```

Note that the extension method does not have a parameter for `format` that you have specified in your config. Instead, when using this extension method, the format is [chosen by the `GetFormatter()` method](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/master/src/Serilog.Sinks.Syslog/SyslogLoggerConfigurationExtensions.cs#L176) and will be [set to the `LocalFormatter` class.](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/master/src/Serilog.Sinks.Syslog/Sinks/Formatters/LocalFormatter.cs)

However, having said all of that, I don't think that is your problem, unless you aren't getting any log messages at all because the configuration doesn't successfully create a logger because of the invalid parameter or something.

I also don't use Linux very much, so to test this, I am just on Windows and created a test project and am using a Fake class to simulate the `LocalSyslogService`, similar to what is done in [the Unit Tests](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/master/test/Serilog.Sinks.Syslog.Tests/LocalSyslogSinkTests.cs).

Here is my complete source code:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Serilog;

using FakeItEasy;
using Serilog.Sinks.Syslog;

namespace ILogger.Sample
{
    public class Program
    {
        private static void Main(string[] args)
        {
            var template = "[{Timestamp:HH:mm:ss} {Level:u3}] {CorrelationId}{Message:lj} {NewLine}{Exception}";
            var templateFormatter = new Serilog.Formatting.Display.MessageTemplateTextFormatter(template, null);

            //var syslogFormatter = new Rfc3164Formatter(Facility.Local0, "TestApp", templateFormatter);
            //var syslogFormatter = new Rfc5424Formatter(Facility.Local0, "TestApp", templateFormatter);
            var syslogFormatter = new LocalFormatter(Facility.Local0, templateFormatter);
            var syslogService = A.Fake<LocalSyslogService>();
            var sink = new SyslogLocalSink(syslogFormatter, syslogService);

            var log = new LoggerConfiguration()
                .WriteTo.Sink(sink)
                .CreateLogger();

            var loggerFactory = (ILoggerFactory)new LoggerFactory();
            loggerFactory.AddSerilog(log);

            var logger = loggerFactory.CreateLogger("Test");

            var context = new Dictionary<string, object>() { ["CorrelationId"] = "<MY_CORRELATION_ID>" };

            using (logger.BeginScope(context))
            {
                logger.LogInformation("Hello");
            }

            sink.Dispose();

            A.CallTo(() => syslogService.Open()).MustHaveHappened();
            A.CallTo(() => syslogService.WriteLog(134, A<string>.That.Contains("<MY_CORRELATION_ID>"))).MustHaveHappened();
            A.CallTo(() => syslogService.Close()).MustHaveHappened();

            var cts = new CancellationTokenSource();

            Console.CancelKeyPress += (sender, eventArgs) =>
            {
                eventArgs.Cancel = true;
            };

            Console.WriteLine("Press CTRL-C or Enter to close.");
            Console.ReadLine();
        }
    }
}
```

And the references:
![image](https://user-images.githubusercontent.com/22459191/134999966-6db39f97-61f9-41d4-929b-177c7c0a21ea.png)

The test validation line of:
```
A.CallTo(() => syslogService.WriteLog(134, A<string>.That.Contains("<MY_CORRELATION_ID>"))).MustHaveHappened();
```

should prove that the `CorrelationId` property and value is being included in the message, and when you run the code it does pass. Going a step further, I can reference the `Serilog.Sinks.Syslog` project code directly (which you see in my picture of references, as opposed to using the NuGet package), and debug that part of the code to find the following:
1. The `LocalFormatter` class is making a call to the base class to render the message:
![image](https://user-images.githubusercontent.com/22459191/135000238-de95bc6d-284c-456d-a59a-3bd033dba4f1.png)
2. And in there we see the `CorrelationId` value being included:
![image](https://user-images.githubusercontent.com/22459191/135000307-05203bab-f7e9-40a5-b1d9-9342b4491b64.png)
3. And lastly, when we actually emit the message, we can see it is still there:
![image](https://user-images.githubusercontent.com/22459191/135000377-0b78341b-3adc-4030-a65b-527fe3bdfcfd.png)

I've also tested the TCP and UDP sinks, and both of those are working as well. So unfortunately I don't know what else to say. I can try getting around to testing it on my Linux machine, but you might be better off going through some of the steps I did and see if you can track down the problem a bit more.

**Comment by GaryHughes** [comment]
Thank you for the detailed response @Kevin-Andrew let me do some further testing based on your guidance and I'll see what I can find.

**Comment by Kevin-Andrew** [comment]
@GaryHughes , we are going to close this issue as we haven't heard back from you.
