### ISSUE TITLE
Add LocalCertificateSelectionCallback to control selection

### ISSUE THREAD

**Issue by sattew** [IonxSolutions/serilog-sinks-syslog#69]
Hi, I'm a little stuck with cert authentication. 

Can we add [LocalCertificateSelectionCallback](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.localcertificateselectioncallback?view=netcore-2.1#system-net-security-sslclientauthenticationoptions-localcertificateselectioncallback) to tcp config and change authentication method. Something like that?

```csharp
    public class SyslogTcpSink : IBatchedLogEventSink, IDisposable
...
   
#if NETCOREAPP2_1_OR_GREATER
                    var certRevocationCheckMode = this.checkCertificateRevocation
                        ? X509RevocationMode.Online
                        : X509RevocationMode.NoCheck;

                    var options = new SslClientAuthenticationOptions
                    {
                        TargetHost = this.Host,
                        ClientCertificates = this.clientCert,
                        CertificateRevocationCheckMode = certRevocationCheckMode,
                        EnabledSslProtocols = SslProtocols.None,
                        LocalCertificateSelectionCallback = this.localCertificateSelectionCallback,
                    };
                    await sslStream.AuthenticateAsClientAsync(options, timeoutCts.Token);
#else
                    // Note that with the .NET 5.0 version of this method and .NET Core 2.1+ of this
                    // method, a cancellation token can be passed directly in as a parameter.
                    await sslStream.AuthenticateAsClientAsync(this.Host, this.clientCert,
                        SslProtocols.None, this.checkCertificateRevocation).ConfigureAwait(false);
#endif

...
```

```csharp
public class SyslogTcpConfig
{
    ...
   #if NETCOREAPP2_1_OR_GREATER
        public LocalCertificateSelectionCallback LocalCertificateSelectionCallback { get; set; }
   #endif
}
```

P.S. I can implement this if it is approved

**Comment by Kevin-Andrew** [comment]
I don't think we'd try to expose that property, or use that property directly since it's not available in the majority of the frameworks we target:
![image](https://github.com/IonxSolutions/serilog-sinks-syslog/assets/22459191/17594574-2d31-45e1-8f3e-e421762d4db8)

We also don't have any conditional compilation within the solution, so I'd hate to start now.

What would be more likely is just creating our own property, or extending something like the `Serilog.Sinks.Syslog.ICertificateProvider` interface. (However, if we added directly to that interface, it would become a breaking change. So it's not very clean.)

Having said that, I'm not sure I understand the use case, versus the obvious of just creating and using a new configuration when the certificate changes. (Which is what we do in our application.)

Since the client certificate authentication is only used with a TCP connection, and since the act of connecting and disconnecting to the Syslog server are not explicitly exposed, I'm not sure when you would use this functionality. I can obviously come up with a derived example, but again, I can also code it such that I have a few different `ILogger` instances defined, or dispose of and create a new instance when the client certificate changes (both of which we do in our application).

I would think that whatever logic you were going to include in the `LocalCertificateSelectionCallback` delegate, would be the same logic that can be specified in a `Serilog.Sinks.Syslog.ICertificateProvider` implementation.

**Comment by sattew** [comment]
Hi. 
I was thinking of extending `ICertificateProvider` and like you said, I don't want to make a breaking change.

My case is the `TcpClient` can't provide a cert without LocalCertificateSelectionCallback. I don't why yet, but I have to work with any syslog servers with any configuration (+ certs).

In my case, I copied the tcp sink and insert the LocalCertificateSelectionCallback. Maybe someone will get stuck in this like I did and it would be great to have a workaround.

**Comment by sattew** [comment]
I've used this simple test rsyslog configuration

```
global(
DefaultNetstreamDriver="gtls"
DefaultNetstreamDriverCAFile="/tmp/ssl/ca.crt"
DefaultNetstreamDriverCertFile="/tmp/ssl/cert.crt"
DefaultNetstreamDriverKeyFile="/tmp/ssl/certkey.key"
)


module(
load="imtcp"
StreamDriver.Name="gtls"
StreamDriver.Mode="1"
StreamDriver.Authmode="x509/fingerprint"
PermittedPeer="SHA1:DC:01:69:BB:F0:0E:6A:3D:28:5A:57:10:B9:16:E3:6F:0F:0B:3D:76" # the same fingerprint as DefaultNetstreamDriverCertFile
)
input(
type="imtcp"
port="6514"
)
```

**Comment by Kevin-Andrew** [comment]
> My case is the TcpClient can't provide a cert without LocalCertificateSelectionCallback. I don't why yet, but I have to work with any syslog servers with any configuration (+ certs).

What `TcpClient` are you referring to? Can you provide a link. I'm not sure I understand your scenario, or why you bring that up. As I mentioned in my first post, this project abstracts all of the TCP connection logic from you. You simply write to a `Serilog` logger that has been configured with this project as a sink. If there is more you can explain, or some sample code as to what you are doing, perhaps that might give me a better idea.

We use this project in an enterprise application used by thousands of companies world wide and have not received any issues about it not being able to connect to their Syslog server. And I even wrote my own Syslog server listener for testing purposes, which again, this project has no problems connecting to, even with client certificate authentication:
![image](https://github.com/IonxSolutions/serilog-sinks-syslog/assets/22459191/2dcab7bc-b13c-4cf5-a2b4-10c89d55df91)

Okay, I just saw your other message about using rsyslog and the configuration. Are you saying that with that configuration, you cannot get a client application that uses this project to successfully connect to the rsyslog server?

**Comment by sattew** [comment]
I can provide link to a repo, but later. `TcpClient ` inside of sink, sorry for misleading you.

About rsyslog configuration, yes. When I'm trying to send the message to syslog. I've got an error in rsyslog: 
`error: peer did not provide a certificate, not permitted to talk to it [v8.2302.0 try https://www.rsyslog.com/e/2085 ]`

We're using .net6 and rsyslog v8.2302.0

**Comment by sattew** [comment]
Oh. we can set localCertificateSelectionCallback in ctor

```csharp
var sslStream = this.certValidationCallback != null
    ? new SslStream(baseStream, true, this.certValidationCallback, userCertificateSelectionCallback: this.localCertificateSelectionCallback)
    : new SslStream(baseStream, true, userCertificateSelectionCallback: this.localCertificateSelectionCallback);

```

**Comment by sattew** [comment]
I think it is compatible with all target frameworks

**Comment by Kevin-Andrew** [comment]
> About rsyslog configuration, yes. When I'm trying to send the message to syslog. I've got an error in rsyslog:
error: peer did not provide a certificate, not permitted to talk to it [v8.2302.0 try https://www.rsyslog.com/e/2085 ]

And then with your other comments, it seems that you are suggesting that if this project, `serilog-sinks-syslog`, were to expose and support something along the lines of the `LocalCertificateSelectionCallback`, that is part of the .NET `TcpClient` and `SslStream`, that the error you are encountering would be corrected, and that your code would be able to successfully connect to your rsyslog server?

Or are you wanting the `LocalCertificateSelectionCallback` to be added for some other reason, like because you need some kind of dynamic certificate selection logic at runtime?

Sorry, I'm still confused.

It seems like you are simply unable to get this `serilog-sinks-syslog` to work with your rsyslog, when using TLS and specifically, client certificate authentication. If that is the case, then implementing something for `LocalCertificateSelectionCallback` is not going to solve your problem.

Unfortunately, I do not know much about Linux, nor rsyslog (the documentation is horrible, in my opinion). But, if you have a Windows machine for testing, I can offer you my little standalone Syslog Server for testing. Then you can use that test console app code you have in https://github.com/sattew/test-rsyslog.

Attached is a complete Visual Studio 2022 solution and some certificate files. If you can't build it yourself, then the binaries are also included. You should be able to run this on any Windows machine with .NET 4.7.2 or greater (like any Windows 10). You'll be running it as an administrator (you should get prompted), and it will create a Firewall rule when started.

The machine you run this on must also have the `DevRoot.cer` certificate added to the machine's Trusted Root Certificate store.

Look at the following screen shot and duplicate the setup:
![image](https://github.com/IonxSolutions/serilog-sinks-syslog/assets/22459191/9f1e8d59-f2aa-4d2e-817f-8ee79e686d89)

Attached is a Zip file of the source code and binaries and certificates. (If you happen to need the password for any of the .pfx files, the password is "password", without the quotes.)

[SyslogServer.zip](https://github.com/IonxSolutions/serilog-sinks-syslog/files/13577806/SyslogServer.zip)

Try it out and ask more questions if necessary, but let's get something working on your end first. Then we can see where to go from there.

**Comment by sattew** [comment]
> And then with your other comments, it seems that you are suggesting that if this project, serilog-sinks-syslog, were to expose and support something along the lines of the LocalCertificateSelectionCallback, that is part of the .NET TcpClient and SslStream, that the error you are encountering would be corrected, and that your code would be able to successfully connect to your rsyslog server?

Yes, I've tested it and it works :)

I'll try your app, thank you.

**Comment by sattew** [comment]
I've figured out the problem. The cert which I set in `CertProvider` wasn't signed via CA, and `SecureChannel` was unable to select the correct certificate and provided nothing.

And when I configure LocalCertificateSelectionCallback, this logic is hidden and the correct certificate is selected (via my callback).
Now I'm thinking should I force to provide any cert (even not sign by CA) or not.

Sorry for wasting your time.

**Comment by Kevin-Andrew** [comment]
That's good to hear, Matthew. I suspected the problem was with the certificates, but wanted to make sure we could get something working first before digging into all of that.

> The cert which I set in `CertProvider` wasn't signed via CA, and `SecureChannel` was unable to select the correct certificate and provided nothing.
> 
> And when I configure `LocalCertificateSelectionCallback`, this logic is hidden and the correct certificate is selected (via my callback).

I may still be a little confused there, sorry. In my experience and understanding, a client application can send the server any certificate it wants to when authenticating. During the TLS handshake, the server will typically send a list of trusted root certificates that it has access to. And there are some client applications, like web browsers, that will filter and restrict what certificates can be sent back since the server typically must be able to validate the certificate, which often means verifying the complete chain of trust of the certificate. With the `LocalCertificateSelectionCallback` delegate, one of the parameters passed to the callback method is an array of `acceptableIssuers` [doc](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.localcertificateselectioncallback?#parameters). Allowing your code to also perform that filtering logic if it wants to.

But by just explicitly setting a client certificate, it doesn't do that filtering and allows you to send anything, as far as I know and have seen. As an example, I created a self-signed certificate for use by the `Serilog.Sinks.Syslog` client, and then set a break point in my Syslog Server test application. The self-signed certificate is not trusted by my machine running the server, nor by the client machine, in any way, yet it was still sent:
![image](https://github.com/IonxSolutions/serilog-sinks-syslog/assets/22459191/a0c33c12-098a-4a94-8c73-e74028d5c332)

But if you got things working and you're happy, that's great. I think we'll close this now. Perhaps if there is more of a demand and a necessary use case for it in the future, we can look into it again.

Thanks.

**Comment by sattew** [comment]
Did you mean that you successfully sent self-signed cert to your Syslog Server app? Hmm... Why the rsyslog got an error "peer doesn't provide certificate", but this is an another case :) 

> Perhaps if there is more of a demand and a necessary use case for it in the future, we can look into it again.

Indeed, thank you!
