### ISSUE TITLE
Load settings from web.config

### ISSUE THREAD

**Issue by asith-w** [IonxSolutions/serilog-sinks-syslog#7]
i am trying to load following settings from web.config file 

```
var log = new LoggerConfiguration()
                .Enrich.WithMachineName()               
                .WriteTo.UdpSyslog(
                    host: "logs2.abc.com", 
                    port: 51333, appName: "gn-TEST", 
                    format: SyslogFormat.RFC5424, 
                    facility: Facility.Local1, 
                    outputTemplate: "{Message}")
                .CreateLogger();
```
 
is there way to load above configuration from appsettings like below 

```
    <add key="serilog:minimum-level" value="Verbose" />
    <add key="serilog:using:SyslogMessages" value="Serilog.Sinks.SyslogMessages" />
    <add key="serilog:write-to:SyslogMessages" />
    <add key="serilog:write-to:SyslogMessages.host" value="logs2.abc.com" />
    <add key="serilog:write-to:SyslogMessages.port" value="51333" />
```

**Comment by colin-anderson** [comment]
Hi! There isn't anything special about configuring this sink compared with any other, but I seem to recall that Serilog's XML config library is less capable than the JSON one (I haven't used XML config for years tho, so that belief may be outdated!).

At a glance, the syntax you show *looks* correct, so as long as you have brought in the Serilog.Appsettings library and are including `.ReadFrom.AppSettings()` when building your logger, then it should work.

If you've tried it and it doesn't work, you can first try enabling Serilog's diagnostic logging to see if you get anything useful. If it still doesn't work, would appreciate if you can let me know, and I'll try to take a look when time permits.

**Comment by colin-anderson** [comment]
Hopefully you got this working with `Serilog.Appsettings`, but just let us know if not

**Comment by timstarbuck** [comment]
For anyone running across this in the future, this seems to work for appsettings configuration.

    <add key="serilog:using:UdpSyslog" value="Serilog.Sinks.Syslog" />
    <add key="serilog:write-to:UdpSyslog" />
    <add key="serilog:write-to:UdpSyslog.host" value="localhost" />
    <add key="serilog:write-to:UdpSyslog.port" value="514" />
