### ISSUE TITLE
Unable to get TCP server to display logs

### ISSUE THREAD

**Issue by rhtnr** [IonxSolutions/serilog-sinks-syslog#8]
I'm having trouble getting to display logs sent by serilog-sinks-syslog to a TCP based syslog endpoint.
UDP seems to be working just fine.

I tried with various syslog servers. All log messages appear in non text form. I tried to play around with format but with no luck. Is there something I'm missing

Apr 14 14:15:40 192.168.17.1 #026#003#003#000▒#001#000#000▒#003#003^▒ō#▒(▒.▒v1$ͼ▒▒)#033x뢚▒#011▒]-$UG#000#000*▒,▒+▒0▒/#000▒#000▒▒$▒#▒(▒'▒

Apr 14 14:15:40 192.168.17.1 ▒#011▒#024▒#023#000▒#000▒#000=#000<#0005#000/

Apr 14 14:15:40 192.168.17.1 #001#000#0007

**Comment by colin-anderson** [comment]
Hmm, I haven't come across this before!

The output you've sent looks like the server is replacing what it believes to be non-printable characters with a visible representation of control codes, such as `#026`.

3 things spring to mind ("1" most likely, "3" least likely):

1. A framing mode is being used that isn't supported by your syslog server
2. TLS is being used, but your syslog server doesn't support it
3. Your syslog server is configured to accept ASCII or Unicode encoded text, rather than UTF8

Would be great if you could provide your sink config (framing type etc) and a syslog server configuration we can use to try to replicate this issue?

**Comment by smr1983** [comment]
Just had almost the same issue in combination with rsyslog and found this post.
 
I had to add two change two settings:
1. Use FramingType.CR
2. Set SslProtocols to None

The total configuration:
loggerConfiguration
     .WriteTo.TcpSyslog(
	configuration.Syslog.Host,
        port: 6514,
	restrictedToMinimumLevel: configuration.LogLevel.Syslog,
	appName: configuration.Syslog.AppName,
	outputTemplate: "{Timestamp:HH:mm:ss}: [{Level}] {Message:lj} {Properties}",
	framingType: FramingType.CR,
	format: SyslogFormat.RFC5424,
	secureProtocols: System.Security.Authentication.SslProtocols.None
);

**Comment by rhtnr** [comment]
Thank you @colin-anderson  and @smr1983 . It was the TLS problem. I didnt know TLS was being used by default

**Comment by colin-anderson** [comment]
@smr1983 @rhtnr glad you both got it working!

`SyslogLoggerConfigurationExtensions.TcpSyslog` uses a "secure by default" approach (we are in the security business, so... 😸), so you will need to disable TLS if your syslog server doesn't support it. We could perhaps make this clearer in the docs though.

Similarly with the framing type, octet counting (as defined in [RFC6587](https://tools.ietf.org/html/rfc6587)) is the most "modern" and capable framing type, so we use it by default. It's difficult to choose a default here though! - can I ask what syslog server you are both using please?

**Comment by rhtnr** [comment]
@colin-anderson Yes, the defaulting to TLS should have hit me :-)
I had used  rsyslog in an Ubuntu machine and kiwi syslog in windows

**Comment by smr1983** [comment]
@colin-anderson I'm using Ubuntu 18.04 LTS in combination with rsyslog 8.32.0
